package com.example.demo.user;

import jakarta.persistence.*;

// Marks this class as a JPA entity, meaning it corresponds to a database table
@Entity
// Specifies the name of the table in the database that this entity will be mapped to
@Table(name = "users")
public class User {

    // Marks this field as the primary key for the entity
    @Id
    // Specifies how the primary key is generated. Here, it will be automatically generated by the database
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    // Specifies the mapping for the 'name' column in the database
    @Column(name="name")
    private String name;

    // Specifies the mapping for the 'email' column in the database
    @Column(name = "email")
    private String email;

    // Getter method for 'id'
    public Long getId() {
        return id;
    }

    // Setter method for 'id'
    public void setId(Long id) {
        this.id = id;
    }

    // Getter method for 'name'
    public String getName() {
        return name;
    }

    // Setter method for 'name'
    public void setName(String name) {
        this.name = name;
    }

    // Getter method for 'email'
    public String getEmail() {
        return email;
    }

    // Setter method for 'email'
    public void setEmail(String email) {
        this.email = email;
    }
}
